apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: {{ .Values.frontend.externalPort }}
    targetPort: {{ .Values.frontend.internalPort }}
  selector:
    app: {{ .Values.frontend.name }}-app
