apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: {{ .Values.frontend.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.frontend.name }}
          servicePort: 80
